services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
    - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
    - mysql-data:/var/lib/mysql
    networks:
    - two_tier
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pTest@123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always
  
  expensesapp:
    build:
      context: .
    image: ${DOCKERHUB_USERNAME}/expenses-tracker-webapp-devops-expensesapp:latest
    container_name: expensesapp
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
    - two_tier
    ports:
    - "8081:8080"
    depends_on:
    - mysql
    restart: always

networks:
  two_tier:
volumes:
  mysql-data:


  




