apiVersion: v1
data:
  MYSQL_DATABASE: ZXhwZW5zZXNfdHJhY2tlcg==
  MYSQL_ROOT_PASSWORD: VGVzdEAxMjM=
kind: Secret
metadata:
  creationTimestamp: "2026-09-09T10:20:24Z"
  name: mysql-secret
  namespace: expensess-app
  resourceVersion: "5893"
  uid: 203b237c-cf13-4672-a156-3ce88d281e62
type: Opaque
