apiVersion: v1
data:
  SPRING_DATASOURCE_PASSWORD: VGVzdEAxMjM=
  SPRING_DATASOURCE_URL: amRiYzpteXNxbDovL215c3FsOjMzMDYvZXhwZW5zZXNfdHJhY2tlcj91c2VTU0w9ZmFsc2UmYWxsb3dQdWJsaWNLZXlSZXRyaWV2YWw9dHJ1ZSZzZXJ2ZXJUaW1lem9uZT1VVEM=
  SPRING_DATASOURCE_USERNAME: cm9vdA==
kind: Secret
metadata:
  name: expensess-secret
  namespace: expensess-app
